name: siegvent2023
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - jupyterlab>=4.0
  - pydicom
  - ipykernel
  - ipywidgets
  - panel
  - pandas
  - nodejs
  - matplotlib
  - scikit-image
  - pygmt
  - geopandas
  - pyproj
  - h5py
  - cmocean
  - rpy2
  - seaborn
